// Realistic seed data for "Orbital Labs", a fictional product company.
// Kept in one place so the shape of the graph is easy to review before loading it.

export const COMPANY = { name: "Orbital Labs" };

export const TEAMS = [
  { name: "Platform Engineering" },
  { name: "Product Design" },
  { name: "Data & ML" },
  { name: "Growth" },
  { name: "Mobile" },
];

export const SKILLS = [
  { name: "React", category: "Frontend" },
  { name: "TypeScript", category: "Frontend" },
  { name: "CSS/Design Systems", category: "Frontend" },
  { name: "Node.js", category: "Backend" },
  { name: "Python", category: "Backend" },
  { name: "Go", category: "Backend" },
  { name: "PostgreSQL", category: "Data" },
  { name: "Graph Databases", category: "Data" },
  { name: "Data Pipelines", category: "Data" },
  { name: "Machine Learning", category: "Data" },
  { name: "AWS", category: "Infrastructure" },
  { name: "Kubernetes", category: "Infrastructure" },
  { name: "CI/CD", category: "Infrastructure" },
  { name: "Product Strategy", category: "Product" },
  { name: "User Research", category: "Product" },
  { name: "Figma", category: "Design" },
  { name: "iOS (Swift)", category: "Mobile" },
  { name: "Android (Kotlin)", category: "Mobile" },
  { name: "Growth Analytics", category: "Growth" },
  { name: "A/B Testing", category: "Growth" },
  { name: "Public Speaking", category: "Leadership" },
  { name: "Technical Writing", category: "Leadership" },
  { name: "Mentoring", category: "Leadership" },
];

// name, title, team, yearsExperience, location
export const PEOPLE = [
  ["Ananya Rao", "Staff Engineer", "Platform Engineering", 9, "Bengaluru"],
  ["Rahul Mehta", "Senior Backend Engineer", "Platform Engineering", 6, "Pune"],
  ["Priya Nair", "Backend Engineer", "Platform Engineering", 3, "Bengaluru"],
  ["Karan Shah", "DevOps Engineer", "Platform Engineering", 5, "Hyderabad"],
  ["Fatima Sheikh", "Engineering Manager", "Platform Engineering", 11, "Delhi"],
  ["Vikram Singh", "Frontend Engineer", "Product Design", 4, "Bengaluru"],
  ["Neha Kulkarni", "Senior Product Designer", "Product Design", 7, "Mumbai"],
  ["Arjun Desai", "Product Designer", "Product Design", 2, "Pune"],
  ["Meera Iyer", "UX Researcher", "Product Design", 5, "Bengaluru"],
  ["Sanjay Gupta", "Design Lead", "Product Design", 10, "Delhi"],
  ["Divya Menon", "Data Scientist", "Data & ML", 6, "Bengaluru"],
  ["Aditya Verma", "ML Engineer", "Data & ML", 4, "Hyderabad"],
  ["Ritu Chawla", "Data Engineer", "Data & ML", 5, "Pune"],
  ["Rohan Kapoor", "Senior Data Scientist", "Data & ML", 8, "Bengaluru"],
  ["Ishaan Malhotra", "Analytics Engineer", "Growth", 3, "Mumbai"],
  ["Pooja Reddy", "Growth Marketing Manager", "Growth", 6, "Bengaluru"],
  ["Aman Khanna", "Growth Engineer", "Growth", 4, "Delhi"],
  ["Sneha Pillai", "Product Manager", "Growth", 7, "Pune"],
  ["Vivek Bhatia", "iOS Engineer", "Mobile", 5, "Bengaluru"],
  ["Tanya Joshi", "Android Engineer", "Mobile", 4, "Hyderabad"],
  ["Aarav Chatterjee", "Mobile Lead", "Mobile", 9, "Bengaluru"],
  ["Kavya Krishnan", "Backend Engineer", "Platform Engineering", 2, "Chennai"],
  ["Nikhil Bansal", "Site Reliability Engineer", "Platform Engineering", 6, "Pune"],
  ["Simran Kaur", "Product Designer", "Product Design", 3, "Delhi"],
  ["Yash Agarwal", "Frontend Engineer", "Growth", 3, "Bengaluru"],
  ["Anushka Rao", "ML Engineer", "Data & ML", 2, "Mumbai"],
  ["Devansh Trivedi", "Engineering Manager", "Data & ML", 10, "Bengaluru"],
  ["Riya Sharma", "Senior Frontend Engineer", "Product Design", 6, "Pune"],
  ["Omkar Patil", "Backend Engineer", "Growth", 4, "Hyderabad"],
  ["Zara Ahmed", "Product Manager", "Mobile", 8, "Bengaluru"],
];

// Explicit "who reports to / sits near whom" style pairs, used to seed
// realistic COLLEAGUE_OF clusters (mostly within-team, some cross-team bridges).
// Index refers to position in PEOPLE array above.
export const COLLEAGUE_EDGES_BY_TEAM = true; // colleagues are generated per-team + a few cross-team bridges in seed.js

// A handful of deliberate cross-team bridge connections, so multi-hop
// "friend of a friend" queries actually cross team boundaries.
export const CROSS_TEAM_BRIDGES = [
  ["Ananya Rao", "Devansh Trivedi"],
  ["Fatima Sheikh", "Sanjay Gupta"],
  ["Neha Kulkarni", "Sneha Pillai"],
  ["Rohan Kapoor", "Ishaan Malhotra"],
  ["Aarav Chatterjee", "Zara Ahmed"],
  ["Karan Shah", "Nikhil Bansal"],
  ["Vikram Singh", "Yash Agarwal"],
  ["Meera Iyer", "Pooja Reddy"],
];

// [personName, skillName, level, years] — level is one of beginner | intermediate | expert
export const HAS_SKILL = [
  ["Ananya Rao", "Go", "expert", 7],
  ["Ananya Rao", "Kubernetes", "expert", 6],
  ["Ananya Rao", "Mentoring", "expert", 8],
  ["Ananya Rao", "AWS", "expert", 6],
  ["Rahul Mehta", "Node.js", "expert", 6],
  ["Rahul Mehta", "PostgreSQL", "intermediate", 4],
  ["Rahul Mehta", "Graph Databases", "intermediate", 2],
  ["Priya Nair", "Node.js", "intermediate", 3],
  ["Priya Nair", "TypeScript", "intermediate", 2],
  ["Karan Shah", "Kubernetes", "expert", 5],
  ["Karan Shah", "CI/CD", "expert", 5],
  ["Karan Shah", "AWS", "intermediate", 4],
  ["Fatima Sheikh", "Mentoring", "expert", 9],
  ["Fatima Sheikh", "Public Speaking", "expert", 8],
  ["Fatima Sheikh", "Go", "intermediate", 5],
  ["Vikram Singh", "React", "expert", 4],
  ["Vikram Singh", "TypeScript", "intermediate", 3],
  ["Vikram Singh", "CSS/Design Systems", "expert", 4],
  ["Neha Kulkarni", "Figma", "expert", 7],
  ["Neha Kulkarni", "User Research", "expert", 6],
  ["Neha Kulkarni", "Mentoring", "intermediate", 4],
  ["Arjun Desai", "Figma", "intermediate", 2],
  ["Meera Iyer", "User Research", "expert", 5],
  ["Sanjay Gupta", "Figma", "expert", 9],
  ["Sanjay Gupta", "Product Strategy", "expert", 8],
  ["Sanjay Gupta", "Mentoring", "expert", 7],
  ["Divya Menon", "Machine Learning", "expert", 6],
  ["Divya Menon", "Python", "expert", 6],
  ["Aditya Verma", "Machine Learning", "intermediate", 4],
  ["Aditya Verma", "Python", "expert", 4],
  ["Ritu Chawla", "Data Pipelines", "expert", 5],
  ["Ritu Chawla", "PostgreSQL", "expert", 5],
  ["Ritu Chawla", "Python", "intermediate", 4],
  ["Rohan Kapoor", "Machine Learning", "expert", 8],
  ["Rohan Kapoor", "Graph Databases", "expert", 4],
  ["Rohan Kapoor", "Mentoring", "expert", 6],
  ["Ishaan Malhotra", "Growth Analytics", "expert", 3],
  ["Ishaan Malhotra", "A/B Testing", "intermediate", 3],
  ["Pooja Reddy", "Growth Analytics", "expert", 6],
  ["Pooja Reddy", "A/B Testing", "expert", 6],
  ["Pooja Reddy", "Product Strategy", "intermediate", 4],
  ["Aman Khanna", "Growth Analytics", "intermediate", 3],
  ["Aman Khanna", "Node.js", "intermediate", 3],
  ["Sneha Pillai", "Product Strategy", "expert", 7],
  ["Sneha Pillai", "A/B Testing", "intermediate", 5],
  ["Vivek Bhatia", "iOS (Swift)", "expert", 5],
  ["Tanya Joshi", "Android (Kotlin)", "expert", 4],
  ["Aarav Chatterjee", "iOS (Swift)", "expert", 8],
  ["Aarav Chatterjee", "Android (Kotlin)", "intermediate", 5],
  ["Aarav Chatterjee", "Mentoring", "expert", 7],
  ["Kavya Krishnan", "Node.js", "beginner", 1],
  ["Kavya Krishnan", "PostgreSQL", "beginner", 1],
  ["Nikhil Bansal", "Kubernetes", "expert", 6],
  ["Nikhil Bansal", "CI/CD", "expert", 6],
  ["Nikhil Bansal", "AWS", "expert", 5],
  ["Simran Kaur", "Figma", "intermediate", 3],
  ["Simran Kaur", "CSS/Design Systems", "intermediate", 2],
  ["Yash Agarwal", "React", "intermediate", 3],
  ["Yash Agarwal", "TypeScript", "beginner", 1],
  ["Anushka Rao", "Machine Learning", "beginner", 1],
  ["Anushka Rao", "Python", "intermediate", 2],
  ["Devansh Trivedi", "Machine Learning", "expert", 8],
  ["Devansh Trivedi", "Mentoring", "expert", 9],
  ["Devansh Trivedi", "Public Speaking", "intermediate", 5],
  ["Riya Sharma", "React", "expert", 6],
  ["Riya Sharma", "TypeScript", "expert", 5],
  ["Riya Sharma", "Technical Writing", "intermediate", 3],
  ["Omkar Patil", "Node.js", "intermediate", 4],
  ["Omkar Patil", "PostgreSQL", "intermediate", 3],
  ["Zara Ahmed", "Product Strategy", "expert", 8],
  ["Zara Ahmed", "User Research", "intermediate", 4],
];
